kind: Secret
apiVersion: v1
metadata:
  name: ssh-credentials
  namespace: tekton
type: Opaque
stringData:
  # ssh-keygen -t ed25519 -C "example.com"
  # cat id_ed25519
  id_ed25519: |
    XXXXXXXX

  #  ssh-keyscan github.com >> githubKey
  # cat githubkey
  known_hosts: |
    XXXXXXXX

  config: |
    IdentityFile ~/.ssh/id_ed25519
---
kind: Secret
apiVersion: v1
metadata:
  name: webhook-secret
  namespace: tekton
type: Opaque
stringData:
  token: "1234567"
